### PR TITLE
Status bar changes

### PR DESCRIPTION
**Pull request by erdemyerebasmaz**
This change removes the need of brightness hack for the status bar blink on opening PodcastDetails page.

If the theme was overridden by the wrapping app, this hack reverted status bar color back to plugins theme. This change is to make sure the status bar color uses the overridden theme.
### Before
https://user-images.githubusercontent.com/4012752/106821785-e1865b00-668e-11eb-8238-7591308a3ce8.mp4
### After
https://user-images.githubusercontent.com/4012752/106817659-3a9ec080-6688-11eb-8b7b-fc194dc01ad4.mp4

### CODE REVIEW

**Comment by roeierez** [comment]
@erdemyerebasmaz the line width at this project is larger than dart defaults (80). This causes the diff to be larger than it needs.
Can you please use line width 130 and change this commit?

**Comment by amugofjava** [comment]
Hi @erdemyerebasmaz,

Looking at the after video, the change that has been made looses the transparency of the status bar. If you look at your before video you can see the podcast is visible through a translucent status bar, but that is lost in the second. It would be great if the Chrome could be handled at the top of the tree, but I don't want to loose that transparency.

**Comment by erdemyerebasmaz** [comment]
> Hi @erdemyerebasmaz,
> 
> Looking at the after video, the change that has been made looses the transparency of the status bar. If you look at your before video you can see the podcast is visible through a translucent status bar, but that is lost in the second. It would be great if the Chrome could be handled at the top of the tree, but I don't want to loose that transparency.

Hello @amugofjava,
I noticed and applied a fix but forgot to update the video. Here's the latest version:

https://user-images.githubusercontent.com/4012752/107884839-23719580-6f08-11eb-87ee-a277ba26e295.mp4

**Comment by amugofjava** [comment]
Hi @erdemyerebasmaz,

Can you please confirm what version of Flutter you are running? I'm trying to merge these changes but I'm getting errors with the `backwardsCompatibility` and `systemOverlayStyle` parameters.

Screenshot from 2021-02-16 09-41-13

I can't see either of them as parameters in the docs.

https://api.flutter.dev/flutter/material/SliverAppBar-class.html

Thanks.

**Comment by erdemyerebasmaz** [comment]
> Hi @erdemyerebasmaz,
> 
> Can you please confirm what version of Flutter you are running? I'm trying to merge these changes but I'm getting errors with the `backwardsCompatibility` and `systemOverlayStyle` parameters.
> 
> Screenshot from 2021-02-16 09-41-13
> 
> I can't see either of them as parameters in the docs.
> 
> https://api.flutter.dev/flutter/material/SliverAppBar-class.html
> 
> Thanks.

Hi @amugofjava,

**flutter --version**
```
Flutter 1.25.0-8.3.pre • channel beta • https://github.com/flutter/flutter.git
Framework • revision 5d36f2e7f5 (5 weeks ago) • 2021-01-14 15:57:49 -0800
Engine • revision 7a8f8ca02c
Tools • Dart 2.12.0 (build 2.12.0-133.7.beta)
```

**Comment by amugofjava** [comment]
Will put this one on hold for now as Anytime is built on stable, and the additional parameters do not seem to be available in stable.

**Comment by amugofjava** [comment]
Hi @erdemyerebasmaz & @roeierez,

I am trying to merge these changes into `master` but I am having issues with the navigation and status bar colors. If you compare `navbar_before.png` (left) showing how it currently looks against `navbar_after.png` (right) after merging these changes you can see that the status and nav bars are not correct. I've tried adding `systemNavigationBarIconBrightness`, `systemNavigationBarColor` and `statusBarBrightness` to the `SystemUiOverlayStyle` but it seems to be ignoring them even though it should honor it on Android 8 and above.

<div>


</div>

Any thoughts?

Thanks.

**Comment by erdemyerebasmaz** [comment]
> Hi @erdemyerebasmaz & @roeierez,
> 
> I am trying to merge these changes into `master` but I am having issues with the navigation and status bar colors. If you compare `navbar_before.png` (left) showing how it currently looks against `navbar_after.png` (right) after merging these changes you can see that the status and nav bars are not correct. I've tried adding `systemNavigationBarIconBrightness`, `systemNavigationBarColor` and `statusBarBrightness` to the `SystemUiOverlayStyle` but it seems to be ignoring them even though it should honor it on Android 8 and above.
> 
>  
> Any thoughts?
> 
> Thanks.

Hi @amugofjava,
The status bar color change was a trade-off due to theme customization purposes. I think overall readability of the status bar has improved. Although, it's not as dramatic as flickering, changing status bar color between contrasting colors is not advised.

Changes to navigation bar on the other hand was an overlooked regression. I was using gesture navigation rather than 3-button navigation on my test device. Now navigation bar uses the bottom app bar color.
I also applied splash color to status & navigation bar on splash screen.

**Comment by erdemyerebasmaz** [comment]
Slash screen on
Debug mode:
https://user-images.githubusercontent.com/4012752/126111765-a1481f51-26b0-478d-a0d6-cc474be590e4.mp4

Release mode:
https://user-images.githubusercontent.com/4012752/126111674-19776be1-2598-419f-bced-c28101a4cff6.mp4

**Comment by erdemyerebasmaz** [comment]
Videoframe_20210719_092006_com huawei himovie overseas
Videoframe_20210719_092015_com huawei himovie overseas

Videoframe_20210719_091948_com huawei himovie overseas
Videoframe_20210719_092022_com huawei himovie overseas

**Comment by amugofjava** [comment]
Thanks @erdemyerebasmaz looks great. I agree that it does look better not switching status bar colour. I have had to make one minor tweak in commenting out `<item name="android:navigationBarColor">@color/splash</item>` in `styles.xml` as the Flutter Chrome settings are only honored in Android 8 and above, so I found this setting resulted in an permanent orange-bar on Android 6 & 7.

**Pull request merged**
