### PR TITLE
Update mini player UI

### PR DESCRIPTION
**Pull request by erdemyerebasmaz**
After consulting with our designer we decided to make these small changes to mini player UI.

- Font changes:
    - Podcast episode title -> **Podcast episode title**
    - **Podcast author** -> Podcast author
    - Authors font size is reduced
    - Both fields now use same letterSpacing and height
 - Play/Pause buttons size is reduced
 - Now has a distinctive background color

### CODE REVIEW

**Comment by amugofjava** [comment]
Hi @erdemyerebasmaz,

With the mini player I have corrected the theming colours for the Scaffold, have aligned the text styling theme with the episode tiles and will be reviewing all text to ensure it is correctly themed so it will fit better with the Breez styling; however, the changes around the mini player colours and play/pause button styling do not fit with the direction I wish to take it so I will be declining those changes.

**Comment by kingonly** [comment]
@amugofjava thanks. Can't we do something dynamic re the colors? What's wrong with the button design?

**Comment by amugofjava** [comment]
Hi @kingonly,

Yes, there must be a theme element we can use for the colours to allow you to apply your theme whilst not affecting it for the standalone version. Perhaps the `cardColor` value could be used as I don't have any cards as such as the moment. What do you think?

In terms of the button design, I sent two screenshots to a few of friends who have not seen my app - one for each design style. They all preferred the slightly larger player icon without the coloured circle background of the original design, and they all preferred the slightly smaller font size on your design as it was clearer and they could see more of the text. So, the commits I have made reflect this.

**Comment by kingonly** [comment]
@amugofjava gotcha. I'll check with @roeierez what can we do here. Re the button, it's hard to argue with users' feedback, so I won, but fyi this change was suggested by our designer, and we like it 🤷‍♂️

**Comment by erdemyerebasmaz** [comment]
> Hi @kingonly,
> 
> Yes, there must be a theme element we can use for the colours to allow you to apply your theme whilst not affecting it for the standalone version. Perhaps the `cardColor` value could be used as I don't have any cards as such as the moment. What do you think?

@amugofjava I think we can use backgroundColor if you merge my changes on podcast_details.

**Comment by amugofjava** [comment]
OK @erdemyerebasmaz, let's try `backgroundColour`. Now i have corrected the Scaffold to use `scaffoldBackgroundColor` as in your PR, backgroundColor is no longer being used anywhere.

**Comment by erdemyerebasmaz** [comment]
@amugofjava Could you also add `mainAxisAlignment: MainAxisAlignment.center,` to mini player's Column? The items are not vertically centered on last build for our use case.

**Comment by amugofjava** [comment]
Sure @erdemyerebasmaz :)

**Comment by erdemyerebasmaz** [comment]
> Sure @erdemyerebasmaz :)

I went ahead and opened a PR https://github.com/amugofjava/anytime_podcast_player/pull/40

**Pull request closed without merging**
