### PR TITLE
Improve Placeholder

### PR DESCRIPTION
**Pull request by erdemyerebasmaz**
Current placeholder is replaced with a container that is colored themes' primaryColor, which fades into the loaded image.

https://user-images.githubusercontent.com/4012752/106625740-0348ea80-6588-11eb-9ce6-422b7c8db9a8.mp4

(_primaryColorLight was used in this video_)

Current placeholder is untouched on errorState except it's color, which changed to errorColor.

Screenshot_20210202_190105_uk me amugofjava anytime

### CODE REVIEW

**Comment by amugofjava** [comment]
Hi @erdemyerebasmaz. I get the idea of this change, but are you having problems with the PRs as you seem to be opening and closing them?

**Comment by erdemyerebasmaz** [comment]
> Hi @erdemyerebasmaz. I get the idea of this change, but are you having problems with the PRs as you seem to be opening and closing them?

Hello @amugofjava ,
Yes, we had an internal misunderstanding on how to merge the changes but it's all good now. Sorry for the pollution :)

**Comment by amugofjava** [comment]
OK, no problem @erdemyerebasmaz. I will try to get to this pull request as soon as I can, but I am also working on some of the placeholders and have replace the cached network library. I'll get to this once I have committed my latest round of changes as it's likely there will be some merge conflicts.

**Comment by erdemyerebasmaz** [comment]
Replaced with #25

**Pull request closed without merging**
