### PR TITLE
#107 Playback progress save.

### LINKED ISSUE #107: Playback progress save.
**Is your feature request related to a problem? Please describe.**
When launching **AnytimePodcast**, I am frustrated to loose the playback progress of episodes I partially played.

It happens when the application is killed (either by system or by user). Then, current playback is not saved.

**Describe the solution you'd like**
I would like to get the playback progress of each episode saved on the fly. So playback could be restored to the play progress I left it.

If episode persistance encounters performances issues, we could update playback time only every 5 seconds, for example.

### PR DESCRIPTION
**Pull request by Chralu**
Fixes #107 

 - Playback state persistance handled by DefaultAudioPlayer only.
 - Playback state saved on every navigation event (so it works when playback is paused too)
 - Playback state saved on playback progress tick.

### CODE REVIEW

**Comment by amugofjava** [comment]
Hi @Chralu,

It is frustrating when Anytime does not save an episode's current position, but I don't believe increasing the update frequency is the solution. Sembast is an in-memory NoSQL store which appends to a file on every write. Writing on every action, especially every 500ms tick, would generate a lot of I/O. A 1 hour show, for example, would generate 7,200 writes.

I would like to better understand how Anytime is failing. When Anytime is playing, it should be less likely to be killed by the OS. When paused, it should have already saved its current position, and when the app is suspended it also saves the current position. What I am not sure about is what happens when Anytime is interrupted by something like a call.

The best solution is one where Anytime correctly handles situations where it needs to save, thus ensuring it does not forget its position whilst minimising the about of I/O.

**Comment by Chralu** [comment]
Hi @amugofjava ,

I agree with you. My solution is a (pretty inefficient) workaround to application brutal stops.

For the story : A few weeks ago, I used to experience application unexpected stops while playing in background (on iOS).
I had no time to investigate, so I have clue of the root issue (maybe is it fixed by now)...

Anyway, would it be pertinent to save playback progress on rewind/fastfoward/seek actions when playback is paused ?

**Comment by amugofjava** [comment]
Hi @Chralu,

When you say it randomly stops on iOS during playback, is the playback just stopping or is the application crashing?

**Comment by Chralu** [comment]
Hi @amugofjava ,

the application was stopped (either crashing or nicely disposed by OS).
So when I re-started it, playback state had not been saved.

**Comment by Chralu** [comment]
Hi @amugofjava 

I don't know if application crashed or stopped 🤔
Maybe AppStore crash logs existence could help to determine this.

**Comment by Chralu** [comment]
I have identified a way to reproduce the behavior. And I think system just stops the application.

1. Start a podcast playback
2. Go on iPhone home page
3. Lock the iPhone

After 15min application is killed by the OS.

If step 2 is omitted (application is in foreground, and phone is locked), then application is not killed by OS.

**Comment by Chralu** [comment]
Related Issue seems fixed.

**Pull request closed without merging**
